server:
  port: 9027
  #使用gzip压缩
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,application/x-javascript,image/svg+xml
    min-response-size: 1024

spring:
  profiles:
    include: route
  application:
    name: gateway
  main:
    web-application-type: reactive  # 使用 Reactive 模型
  cloud:
    nacos:
      # Nacos Config 配置项，对应 NacosConfigProperties 配置属性类
      config:
        server-addr: localhost:8848 # Nacos 服务器地址
        namespace: ""  # 使用的 Nacos 的命名空间，默认为 null
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600